### ISSUE TITLE
npm install is failing on iojs v3.0.0

### ISSUE THREAD

**Issue by daleharvey** [Level/leveldown#211]
Seeing a different error locally as well as a permafail on travis

https://s3.amazonaws.com/archive.travis-ci.org/jobs/74904011/log.txt is the travis log (https://travis-ci.org/pouchdb/pouchdb/jobs/74904011 is the run)

On a local install - https://gist.github.com/daleharvey/c8956054681e14ea192e

**Comment by jekrb** [comment]
I ran into the same issue yesterday, it seems there is a pending pull request to fix it: #195 

For the time being I'm just installing that `leveldown` branch.

```
npm i github://Level/leveldown#iojs-v3-nan-next  levelup -S
```

and using `levelup` instead of `level`
```
const level = require('levelup') // rather than require('level')
```

**Comment by jekrb** [comment]
I think everything has been addressed with #195 & #212 as I'm not having any issues installing on io.js 3 any more :)

Thanks @mafintosh @rvagg @kkoopa @ralphtheninja  @dominictarr @juliangruber !

**Comment by juliangruber** [comment]
sweet, @daleharvey can you confirm?

**Comment by daleharvey** [comment]
Hrm, I am still seeing failure to install on travis, https://api.travis-ci.org/jobs/75824033/log.txt?deansi=true is the log

```
In file included from /home/travis/.node-gyp/3.0.0/include/node/node.h:42:0,
                 from ../src/batch.cc:1:
/home/travis/.node-gyp/3.0.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
```

**Comment by rvagg** [comment]
probably a compiler version error, see [here](https://github.com/Level/leveldown/pull/212#issuecomment-131396402) @daleharvey

**Comment by ralphtheninja** [comment]
@daleharvey Is this still an issue? Please close if that's the case. Thanks!

**Comment by daleharvey** [comment]
Once I updated to g++4.8 I have started seeing new errors

```
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:5:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
```

Basing my changes to .travis.yml mostly off the leveldown travis.yml so not sure whats up here either

**Comment by daleharvey** [comment]
I think that actually needs a level upgrade to be supported right? thats still in progress for pouch so will close this out
